#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

# the script will exit if there is any error
set -e
cd compressible && wmake -j && cd -
cd incompressible && wmake -j && cd -
# disable the -e flag
set +e


