#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

cd src/adjoint && ./Allclean && cd -
cd src/pyDASolvers && ./Allclean && cd -
cd src/utilities/coloring && ./Allclean && cd -
cd src/utilities/postProcessing && ./Allclean && cd -
cd tests && ./Allclean && cd -
