#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

cd src/adjoint && rm -rf lnInclude && cd -
cd src/adjoint/DAUtility && wclean && cd -
