#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

function cleanDAFoam()
{ 
  cd src/adjoint && rm -rf lnInclude && cd -
  cd src/adjoint && wclean && cd -
  cd src/newTurbModels && ./Allclean && cd -
  cd src/pyUnitTests && ./Allclean && cd -
  cd src/pyDASolvers && ./Allclean && cd -
  cd src/utilities/preProcessing && ./Allclean && cd -
}

# clean original mode
echo "***************** Cleaning original mode **************"
. $DAFOAM_ROOT_PATH/loadDAFoam.sh
cleanDAFoam
# clean ADR mode
echo "***************** Cleaning ADR mode **************"
. $DAFOAM_ROOT_PATH/loadDAFoam.sh
. $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-v1812-ADR/etc/bashrc
cleanDAFoam
# if COMPILE_DAFOAM_ADF is set, compile ADF mode
if [ -z "$COMPILE_DAFOAM_ADF" ]; then
  echo "COMPILE_DAFOAM_ADF is not set. skip the ADF mode"
else
  echo "***************** Cleaning ADF mode **************"
  . $DAFOAM_ROOT_PATH/loadDAFoam.sh
  . $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-v1812-ADF/etc/bashrc
  cleanDAFoam
fi

# reset the OpenFOAM environment to the original mode
. $DAFOAM_ROOT_PATH/loadDAFoam.sh


