#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

function makeDAFoam()
{ 
  # the script will exit if there is any error
  set -e
  wmakeLnInclude src/adjoint
  cd src/adjoint && wmake -j && cd -
  cd src/newTurbModels && ./Allmake && cd -
  cd src/pyUnitTests && ./Allmake && cd -
  cd src/pyDASolvers && ./Allmake && cd -
  cd src/utilities/preProcessing && ./Allmake && cd -
  # disable the -e flag
  set +e
}

# compile original mode
echo "***************** Compiling original mode **************"
. $DAFOAM_ROOT_PATH/loadDAFoam.sh
makeDAFoam
# compile ADR mode
echo "***************** Compiling ADR mode **************"
. $DAFOAM_ROOT_PATH/loadDAFoam.sh
. $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-v1812-ADR/etc/bashrc
makeDAFoam
# if COMPILE_DAFOAM_ADF is set, compile ADF mode
if [ -z "$COMPILE_DAFOAM_ADF" ]; then
  echo "COMPILE_DAFOAM_ADF is not set. skip the ADF mode"
else
  echo "***************** Compiling ADF mode **************"
  . $DAFOAM_ROOT_PATH/loadDAFoam.sh
  . $DAFOAM_ROOT_PATH/OpenFOAM/OpenFOAM-v1812-ADF/etc/bashrc
  makeDAFoam
fi

# reset the OpenFOAM environment to the original mode
. $DAFOAM_ROOT_PATH/loadDAFoam.sh

pip install .

ls -R dafoam/libs && echo " " && echo "*** Build Successful! ***" && echo " "