#!/usr/bin/env bash

# the script will exit if there is any error
set -e

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

wmakeLnInclude src/adjoint
cd src/adjoint && ./Allmake && cd -
cd src/pyUnitTests && ./Allmake && cd -
cd src/pyDASolvers && ./Allmake && cd -
cd src/utilities/coloring && ./Allmake && cd -
echo "******* DAFoam $WM_CODI_AD_LIB_POSTFIX compilation finished! *********"