#!/usr/bin/env bash
# Clean DAFoam

rm *.pyc
rm -rf __pycache__
rm python/*.pyc
rm -rf python/__pycache__
rm python/scripts/*.pyc
rm -rf python/scripts/__pycache__
rm python/reg_tests/*.pyc
rm -rf python/reg_tests/__pycache__
rm python/reg_tests/tests/*.pyc
rm -rf python/reg_tests/tests/__pycache__
rm python/reg_tests/dafoam*reg*

if [ -z "$DF_CleanDoc" ]; then
    export DF_CleanDoc=True
fi
if [ "$DF_CleanDoc" = "True" ]; then
  rm -rf doc/build
  rm -rf doc/DAFoamDoc.html
  rm -rf doc/source/_static/OpenFOAM
  rm -rf doc/source/_static/Python
fi

cd src/ofLibs/myLibs
./Allwclean
cd ../../../

cd src/ofLibs
wclean
rm Make/options Make/files

cd ../../applications/coloringSolverIncompressible
wclean
rm Make/options

cd ../simpleDAFoam
wclean
rm Make/options

cd ../simpleTDAFoam
wclean
rm Make/options

cd ../buoyantBoussinesqSimpleDAFoam
wclean
rm Make/options

cd ../laplacianDAFoam
wclean
rm Make/options

cd ../scalarTransportDAFoam
wclean
rm Make/options

cd ../solidDisplacementDAFoam
wclean
rm Make/options

cd ../coloringSolverCompressible
wclean
rm Make/options

cd ../rhoSimpleDAFoam
wclean
rm Make/options

cd ../rhoSimpleCDAFoam
wclean
rm Make/options

cd ../buoyantSimpleDAFoam
wclean
rm Make/options

cd ../turboDAFoam
wclean
rm Make/options

cd ../utilities
./Allwclean


cd ../

