#!/usr/bin/env bash
# Compile DAFoam

# first check if we need to compile the DAFoam doc
if [ -z "$DF_CompileDoc" ]; then
    export DF_CompileDoc=False
fi

if [ "$DF_CompileDoc" = "True" ]; then
    cd doc
    ./Allwmake
    cd ../
fi

# now compile DAFoam
# can be either Opt or Debug; default: Opt
if [ -z "$DF_CompileMode" ]; then
    export DF_CompileMode=Opt
fi

echo "CompileMode: ${DF_CompileMode}"
sleep 1

function makeIncompressible() 
{
    if [ -f Make/files_Incompressible ]; then
        cp Make/files_Incompressible Make/files
    fi
    cp Make/options_Incompressible Make/options
    sed -i '4i\    \-DIncompressibleFlow \\' Make/options
    if [ "$DF_CompileMode" = "Debug" ]; then
        sed -i '4i\    \-DFULLDEBUG -g -O0 \\' Make/options
    fi
    wmake
}

function makeCompressible() 
{
    if [ -f Make/files_Compressible ]; then
        cp Make/files_Compressible Make/files
    fi
    cp Make/options_Compressible Make/options
    sed -i '4i\    \-DCompressibleFlow \\' Make/options
    if [ "$DF_CompileMode" = "Debug" ]; then
        sed -i '4i\    \-DFULLDEBUG -g -O0 \\' Make/options
    fi
    wmake
}

echo "************** Compiling prerequisite Libraries **************"
sleep 1

cd src/ofLibs/myLibs
./Allwmake
cd ../../../

echo "************** Compiling Incompressible Adjoint Solvers **************"
sleep 1

cd src/ofLibs
makeIncompressible

cd ../../applications/coloringSolverIncompressible
makeIncompressible

cd ../simpleDAFoam
makeIncompressible

cd ../simpleTDAFoam
makeIncompressible

cd ../buoyantBoussinesqSimpleDAFoam
makeIncompressible

cd ../laplacianDAFoam
makeIncompressible

cd ../scalarTransportDAFoam
makeIncompressible

cd ../solidDisplacementDAFoam
makeIncompressible

cd ../../

export DF_CleanDoc=False
./Allwclean

echo "************** Compiling Compressible Adjoint Solvers **************"
sleep 1

cd src/ofLibs
makeCompressible

cd ../../applications/coloringSolverCompressible
makeCompressible

cd ../rhoSimpleDAFoam
makeCompressible

cd ../rhoSimpleCDAFoam
makeCompressible

cd ../turboDAFoam
makeCompressible

cd ../buoyantSimpleDAFoam
makeCompressible

cd ../../

echo "************** Compiling Utilities **************"
sleep 1

cd applications/utilities
./Allwmake

cd ../../

echo "************** Compiling pyLibs **************"
cd src/pyLibs
./Allmake
