#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

if [ "$WM_CODI_AD_LIB_POSTFIX" = "ADR" ]; then
  echo "ADR mode found. Skip the preProcessing build"
elif [ "$WM_CODI_AD_LIB_POSTFIX" = "ADF" ]; then
  echo "ADF mode found. Skip the preProcessing build"
else
  for d in ./*/ ; do 
    cd "$d" 
    wmake
    cd ../
  done
fi