#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

# check if we need to download reg_test_files-main.tar.gz
if [ -f "reg_test_files-main.tar.gz" ]; then
  echo "reg_test_files-main.tar.gz already exists."
else
  echo "Downloading reg_test_files-main.tar.gz"
  wget https://github.com/DAFoam/reg_test_files/archive/refs/heads/main.tar.gz -O reg_test_files-main.tar.gz --no-check-certificate
fi

function runTests() 
{
  rm -rf reg_test_files-main
  tar -zxf reg_test_files-main.tar.gz
  mpirun --oversubscribe -np 4 python runTests_${1}.py 
}

runTests DAUtility
runTests DASimpleFoam
