#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

for d in ./*/ ; do 
  cd "$d"
  rm -rf *.cpp *.so build 
  cd ../
done

