#!/usr/bin/env bash

# the script will exit if there is any error
set -e

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

if [ "$WM_CODI_AD_LIB_POSTFIX" = "ADR" ]; then
  echo "ADR mode found. Skip the pyColoring build"
elif [ "$WM_CODI_AD_LIB_POSTFIX" = "ADF" ]; then
  echo "ADF mode found. Skip the pyColoring build"
else
  cythonize -3 pyColoring.pyx
  wmake -j
  cp -r pyColoring$WM_CODI_AD_LIB_POSTFIX.so ../../../dafoam/libs/$WM_CODI_AD_LIB_POSTFIX/pyColoring.$(python3 -c 'import sysconfig; ext_suffix = sysconfig.get_config_var("EXT_SUFFIX"); print(ext_suffix.split(".")[1])').so
fi

