#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

for d in ./*/ ; do 
  cd "$d"
  if test -f Make/files ; then
    wclean
  fi
  cd ../
done

