#!/usr/bin/env bash

if [ -z "$WM_PROJECT" ]; then
  echo "OpenFOAM environment not found, forgot to source the OpenFOAM bashrc?"
  exit 1
fi

cp Make/files_Incompressible Make/files
cp Make/options_Incompressible Make/options
sed -i 's/-std=c++11/-std=c++11 -DFULLDEBUG -g -O0/g' Make/options
wmake